Repository jenkinsci/rest-list-parameter-plugin, pull requests merged in 2022-06, with the labels that each got.

#133 Fix typo
  src/main/resources/io/jenkins/plugins/restlistparam/RestListParameterDefinition/help-defaultValue.html
Labels: documentation

#134 fix: codeQL warnings
  src/main/java/io/jenkins/plugins/restlistparam/RestListParameterDefinition.java
  src/main/java/io/jenkins/plugins/restlistparam/RestListParameterGlobalConfig.java
Labels: chore

#136 fix: refresh values list if empty on param value creation
  src/main/java/io/jenkins/plugins/restlistparam/RestListParameterDefinition.java
Labels: bugfix
